# Generated by Django 3.2 on 2021-04-29 03:40

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210427_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(upload_to='gallery', validators=[main.validators.clean_picture]),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news', validators=[main.validators.news_picture]),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='image',
            field=models.ImageField(upload_to='staff', validators=[main.validators.staff_picture]),
        ),
    ]
